blank_issues_enabled: false
contact_links:
  - name: 🤔 Question or Discussion
    url: https://github.com/aoshimash/crawld/discussions
    about: Ask questions or discuss ideas about crawld
  - name: 📚 Documentation
    url: https://github.com/aoshimash/crawld/blob/main/README.md
    about: Check the documentation and usage examples
