blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/aoshimash/urlmap/discussions
    about: Ask questions or discuss ideas about urlmap
  - name: 📚 Documentation
    url: https://github.com/aoshimash/urlmap/blob/main/README.md
    about: Read the documentation
